name: Cargo Update Bot 🤖
on:
  schedule:
    - cron: "0 0 * * 1"
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Install Rust
      run: |
        rm -f ~/.cargo/bin/*
        curl --proto '=https' --tlsv1.3 -sSf https://sh.rustup.rs | sh -s -- -y
    - name: Install toolchain
      run: | 
        rustup toolchain install nightly
        rustup default nightly
    - name: Bot 🤖 "Updating Carogo Dependencies..."
      run: |
        cd airconnect.rs
        cargo update
        cd flatpatch.rs
        cargo update
        git config --global user.name 'Cargo Update Bot'
        git config --global user.email 'cargoupbot@users.noreply.github.com'
        git add .
        git commit -am "cargo: update dependencies" || true
        git push
