name: Rust
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
    steps:
    - uses: actions/checkout@main
    - name: Install Rust
      run: |
        rm -f ~/.cargo/bin/*
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - name: Install toolchain
      run: | 
        rustup toolchain install ${{ matrix.rust }}
        rustup default ${{ matrix.rust }}
    - name: Build
      run: |
        cd guessing_game
        cargo build --verbose
    - name: Run tests
      run: |
        cd guessing_game
        cargo test --verbose

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust
        run: |
          rm -f ~/.cargo/bin/*
          curl https://sh.rustup.rs -sSf | sh -s -- -y
      - name: Install toolchain
        run: |
          rustup toolchain install stable
          rustup default stable
      - name: Check formatting
        run: cargo fmt -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust
        run: |
          rm -f ~/.cargo/bin/*
          curl https://sh.rustup.rs -sSf | sh -s -- -y
      - name: Install toolchain
        run: | 
          rustup toolchain install nightly
          rustup default nightly
      - name: Validate clippy
        run: cargo clippy
