name: Rust
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Run
      run: |
        rm -f ~/.cargo/bin/*
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        cd src/guessing_game
        cargo build --verbose
    - name: Run tests
      run: |
        cd src/bin
        cargo test --verbose
